Attempt to add GH Actions
valkum/conduit pull request #1
Opened 2020-05-06 12:34 UTC by valkum

2020-05-07 15:33 UTC, timokoesters requested changes

2020-05-07 15:33 UTC, timokoesters commented on src/database.rs
> +        let path = config.get_str("database_path").unwrap_or(&fallback_path.to_str().unwrap());
Can you use unwrap_or_else here and calculate the fallback path in there?

2020-05-07 15:33 UTC, timokoesters commented on src/main.rs
> +
Run cargo fmt

2020-05-07 15:33 UTC, timokoesters commented on src/main.rs
> +
I don't think we need the structopt dependency just for this. Can you remove this and just use std::env::args directly?

2020-05-16 18:13 UTC, valkum commented
Got merged upstream

2020-05-16 18:13 UTC, closed without merging